// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The sentiment analysis response message.
public struct AnalyzeSentimentResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The overall sentiment of the input document.
  public var documentSentiment: Sentiment? = nil

  /// The language of the text, which will be the same as the language specified
  /// in the request or, if not specified, the automatically-detected language.
  /// See [Document.language][] field for more details.
  public var languageCode: Swift.String = Swift.String()

  /// The sentiment for all the sentences in the document.
  public var sentences: [Sentence] = []

  /// Whether the language is officially supported. The API may still return a
  /// response when the language is not supported, but it is on a best effort
  /// basis.
  public var languageSupported: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AnalyzeSentimentResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnalyzeSentimentResponse().with { $0.documentSentiment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let documentSentiment = CodingKeys(stringValue: "documentSentiment")
    static let languageCode = CodingKeys(stringValue: "languageCode")
    static let sentences = CodingKeys(stringValue: "sentences")
    static let languageSupported = CodingKeys(stringValue: "languageSupported")

    static let _knownKeys: Set<Swift.String> = [
      "documentSentiment",
      "languageCode",
      "sentences",
      "languageSupported",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.documentSentiment = try container.decodeIfPresent(
      Sentiment.self, forKey: .documentSentiment)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageCode) {
      self.languageCode = value
    }
    if let value = try container.decodeIfPresent([Sentence].self, forKey: .sentences) {
      self.sentences = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .languageSupported) {
      self.languageSupported = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.documentSentiment, forKey: .documentSentiment)
    try container.encode(self.languageCode, forKey: .languageCode)
    try container.encode(self.sentences, forKey: .sentences)
    try container.encode(self.languageSupported, forKey: .languageSupported)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.language.v2.AnalyzeSentimentResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
