// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a phrase in the text that is a known entity, such as
/// a person, an organization, or location. The API associates information, such
/// as probability and mentions, with entities.
public struct Entity: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The representative name for the entity.
  public var name: Swift.String = Swift.String()

  /// The entity type.
  public var type: Entity.Type_ = Entity.Type_()

  /// Metadata associated with the entity.
  ///
  /// For the metadata
  /// associated with other entity types, see the Type table below.
  public var metadata: [Swift.String: Swift.String] = [:]

  /// The mentions of this entity in the input document. The API currently
  /// supports proper noun mentions.
  public var mentions: [EntityMention] = []

  /// For calls to [AnalyzeEntitySentiment][] or if
  /// [AnnotateTextRequest.Features.extract_entity_sentiment][google.cloud.language.v2.AnnotateTextRequest.Features.extract_entity_sentiment]
  /// is set to true, this field will contain the aggregate sentiment expressed
  /// for this entity in the provided document.
  public var sentiment: Sentiment? = nil

  /// Initialize a new instance of `Entity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Entity().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The type of the entity. The table
  /// below lists the associated fields for entities that have different
  /// metadata.
  public enum Type_: Codable, Equatable, Sendable {
    /// Unknown
    case unknown
    /// Person
    case person
    /// Location
    case location
    /// Organization
    case organization
    /// Event
    case event
    /// Artwork
    case workOfArt
    /// Consumer product
    case consumerGood
    /// Other types of entities
    case other
    /// Phone number
    ///
    /// The metadata lists the phone number, formatted according to local
    /// convention, plus whichever additional elements appear in the text:
    ///
    /// * `number` - the actual number, broken down into sections as per local
    /// convention
    /// * `national_prefix` - country code, if detected
    /// * `area_code` - region or area code, if detected
    /// * `extension` - phone extension (to be dialed after connection), if
    /// detected
    case phoneNumber
    /// Address
    ///
    /// The metadata identifies the street number and locality plus whichever
    /// additional elements appear in the text:
    ///
    /// * `street_number` - street number
    /// * `locality` - city or town
    /// * `street_name` - street/route name, if detected
    /// * `postal_code` - postal code, if detected
    /// * `country` - country, if detected
    /// * `broad_region` - administrative area, such as the state, if detected
    /// * `narrow_region` - smaller administrative area, such as county, if
    /// detected
    /// * `sublocality` - used in Asian addresses to demark a district within a
    /// city, if detected
    case address
    /// Date
    ///
    /// The metadata identifies the components of the date:
    ///
    /// * `year` - four digit year, if detected
    /// * `month` - two digit month number, if detected
    /// * `day` - two digit day number, if detected
    case date
    /// Number
    ///
    /// The metadata is the number itself.
    case number
    /// Price
    ///
    /// The metadata identifies the `value` and `currency`.
    case price
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .person: return 1
      case .location: return 2
      case .organization: return 3
      case .event: return 4
      case .workOfArt: return 5
      case .consumerGood: return 6
      case .other: return 7
      case .phoneNumber: return 9
      case .address: return 10
      case .date: return 11
      case .number: return 12
      case .price: return 13
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unknown: return "UNKNOWN"
      case .person: return "PERSON"
      case .location: return "LOCATION"
      case .organization: return "ORGANIZATION"
      case .event: return "EVENT"
      case .workOfArt: return "WORK_OF_ART"
      case .consumerGood: return "CONSUMER_GOOD"
      case .other: return "OTHER"
      case .phoneNumber: return "PHONE_NUMBER"
      case .address: return "ADDRESS"
      case .date: return "DATE"
      case .number: return "NUMBER"
      case .price: return "PRICE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNKNOWN": self = .unknown
      case "PERSON": self = .person
      case "LOCATION": self = .location
      case "ORGANIZATION": self = .organization
      case "EVENT": self = .event
      case "WORK_OF_ART": self = .workOfArt
      case "CONSUMER_GOOD": self = .consumerGood
      case "OTHER": self = .other
      case "PHONE_NUMBER": self = .phoneNumber
      case "ADDRESS": self = .address
      case "DATE": self = .date
      case "NUMBER": self = .number
      case "PRICE": self = .price
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .person
      case 2: self = .location
      case 3: self = .organization
      case 4: self = .event
      case 5: self = .workOfArt
      case 6: self = .consumerGood
      case 7: self = .other
      case 9: self = .phoneNumber
      case 10: self = .address
      case 11: self = .date
      case 12: self = .number
      case 13: self = .price
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode(0)
      case .person: return try container.encode(1)
      case .location: return try container.encode(2)
      case .organization: return try container.encode(3)
      case .event: return try container.encode(4)
      case .workOfArt: return try container.encode(5)
      case .consumerGood: return try container.encode(6)
      case .other: return try container.encode(7)
      case .phoneNumber: return try container.encode(9)
      case .address: return try container.encode(10)
      case .date: return try container.encode(11)
      case .number: return try container.encode(12)
      case .price: return try container.encode(13)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.language.v2.Entity"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
