// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  class LanguageServiceTransport: LanguageServiceStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://language.googleapis.com",
      )
    }

    public func analyzeSentiment(
      request: AnalyzeSentimentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnalyzeSentimentResponse {
      let path = try { () throws -> Swift.String in
        return "/v2/documents:analyzeSentiment"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudLanguageV2.AnalyzeSentimentResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func analyzeEntities(
      request: AnalyzeEntitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse {
      let path = try { () throws -> Swift.String in
        return "/v2/documents:analyzeEntities"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudLanguageV2.AnalyzeEntitiesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func classifyText(
      request: ClassifyTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.ClassifyTextResponse {
      let path = try { () throws -> Swift.String in
        return "/v2/documents:classifyText"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudLanguageV2.ClassifyTextResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func moderateText(
      request: ModerateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.ModerateTextResponse {
      let path = try { () throws -> Swift.String in
        return "/v2/documents:moderateText"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudLanguageV2.ModerateTextResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func annotateText(
      request: AnnotateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnnotateTextResponse {
      let path = try { () throws -> Swift.String in
        return "/v2/documents:annotateText"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudLanguageV2.AnnotateTextResponse.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
