// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleCloudGax

extension Clients {
  protocol LanguageServiceStub: Sendable {
    func analyzeSentiment(
      request: AnalyzeSentimentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnalyzeSentimentResponse

    func analyzeEntities(
      request: AnalyzeEntitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse

    func classifyText(
      request: ClassifyTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.ClassifyTextResponse

    func moderateText(
      request: ModerateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.ModerateTextResponse

    func annotateText(
      request: AnnotateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnnotateTextResponse
  }
}
