// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class LanguageServiceLogging: LanguageServiceStub {
    let inner: any LanguageServiceStub
    let logger: Logger

    public init(_ inner: any LanguageServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-language-v2"
      logger[metadataKey: "gcp.client.service"] = "language"
      logger[metadataKey: "gcp.experimental.swift.client"] = "LanguageService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func analyzeSentiment(
      request: AnalyzeSentimentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnalyzeSentimentResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "analyzeSentiment",
        action: {
          (r: AnalyzeSentimentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLanguageV2.AnalyzeSentimentResponse
          in
          return try await self.inner.analyzeSentiment(request: r, options: o)
        })
    }

    public func analyzeEntities(
      request: AnalyzeEntitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "analyzeEntities",
        action: {
          (r: AnalyzeEntitiesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse
          in
          return try await self.inner.analyzeEntities(request: r, options: o)
        })
    }

    public func classifyText(
      request: ClassifyTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.ClassifyTextResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "classifyText",
        action: {
          (r: ClassifyTextRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLanguageV2.ClassifyTextResponse
          in
          return try await self.inner.classifyText(request: r, options: o)
        })
    }

    public func moderateText(
      request: ModerateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.ModerateTextResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "moderateText",
        action: {
          (r: ModerateTextRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLanguageV2.ModerateTextResponse
          in
          return try await self.inner.moderateText(request: r, options: o)
        })
    }

    public func annotateText(
      request: AnnotateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnnotateTextResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "annotateText",
        action: {
          (r: AnnotateTextRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLanguageV2.AnnotateTextResponse
          in
          return try await self.inner.annotateText(request: r, options: o)
        })
    }
  }
}
