// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax

/// Provides text analysis operations such as sentiment analysis and entity
/// recognition.
///
/// @Snippet(path: "LanguageServiceQuickstart")
public final class LanguageServiceClient: Clients.LanguageServiceProtocol, Sendable {
  let inner: any Clients.LanguageServiceStub

  /// Creates a new `LanguageServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.LanguageServiceStub = try Clients.LanguageServiceTransport(options)
    inner = Clients.LanguageServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.LanguageServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Analyzes the sentiment of the provided text.
  ///
  /// @Snippet(path: "LanguageService_AnalyzeSentiment")
  public func analyzeSentiment(
    request: AnalyzeSentimentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLanguageV2.AnalyzeSentimentResponse {
    try await self.inner.analyzeSentiment(request: request, options: options)
  }

  /// Finds named entities (currently proper names and common nouns) in the text
  /// along with entity types, probability, mentions for each entity, and
  /// other properties.
  ///
  /// @Snippet(path: "LanguageService_AnalyzeEntities")
  public func analyzeEntities(
    request: AnalyzeEntitiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse {
    try await self.inner.analyzeEntities(request: request, options: options)
  }

  /// Classifies a document into categories.
  ///
  /// @Snippet(path: "LanguageService_ClassifyText")
  public func classifyText(
    request: ClassifyTextRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLanguageV2.ClassifyTextResponse {
    try await self.inner.classifyText(request: request, options: options)
  }

  /// Moderates a document for harmful and sensitive categories.
  ///
  /// @Snippet(path: "LanguageService_ModerateText")
  public func moderateText(
    request: ModerateTextRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLanguageV2.ModerateTextResponse {
    try await self.inner.moderateText(request: request, options: options)
  }

  /// A convenience method that provides all features in one call.
  ///
  /// @Snippet(path: "LanguageService_AnnotateText")
  public func annotateText(
    request: AnnotateTextRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLanguageV2.AnnotateTextResponse {
    try await self.inner.annotateText(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `LanguageServiceClient`.
  ///
  /// To mock `LanguageServiceClient` change your functions to receive
  /// `some LanguageServiceProtocol` or `any LanguageServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol LanguageServiceProtocol {
    /// See `LanguageServiceClient.analyzeSentiment`.
    func analyzeSentiment(request: AnalyzeSentimentRequest) async throws
      -> GoogleCloudLanguageV2.AnalyzeSentimentResponse

    /// See `LanguageServiceClient.analyzeSentiment`.
    func analyzeSentiment(
      document: Document?,
      encodingType: EncodingType,
    ) async throws -> GoogleCloudLanguageV2.AnalyzeSentimentResponse

    /// See `LanguageServiceClient.analyzeSentiment`.
    func analyzeSentiment(
      document: Document?,
    ) async throws -> GoogleCloudLanguageV2.AnalyzeSentimentResponse

    /// See `LanguageServiceClient.analyzeEntities`.
    func analyzeEntities(request: AnalyzeEntitiesRequest) async throws
      -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse

    /// See `LanguageServiceClient.analyzeEntities`.
    func analyzeEntities(
      document: Document?,
      encodingType: EncodingType,
    ) async throws -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse

    /// See `LanguageServiceClient.analyzeEntities`.
    func analyzeEntities(
      document: Document?,
    ) async throws -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse

    /// See `LanguageServiceClient.classifyText`.
    func classifyText(request: ClassifyTextRequest) async throws
      -> GoogleCloudLanguageV2.ClassifyTextResponse

    /// See `LanguageServiceClient.classifyText`.
    func classifyText(
      document: Document?,
    ) async throws -> GoogleCloudLanguageV2.ClassifyTextResponse

    /// See `LanguageServiceClient.moderateText`.
    func moderateText(request: ModerateTextRequest) async throws
      -> GoogleCloudLanguageV2.ModerateTextResponse

    /// See `LanguageServiceClient.moderateText`.
    func moderateText(
      document: Document?,
    ) async throws -> GoogleCloudLanguageV2.ModerateTextResponse

    /// See `LanguageServiceClient.annotateText`.
    func annotateText(request: AnnotateTextRequest) async throws
      -> GoogleCloudLanguageV2.AnnotateTextResponse

    /// See `LanguageServiceClient.annotateText`.
    func annotateText(
      document: Document?,
      features: AnnotateTextRequest.Features?,
      encodingType: EncodingType,
    ) async throws -> GoogleCloudLanguageV2.AnnotateTextResponse

    /// See `LanguageServiceClient.annotateText`.
    func annotateText(
      document: Document?,
      features: AnnotateTextRequest.Features?,
    ) async throws -> GoogleCloudLanguageV2.AnnotateTextResponse

    /// See `LanguageServiceClient.analyzeSentiment`.
    func analyzeSentiment(
      request: AnalyzeSentimentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnalyzeSentimentResponse

    /// See `LanguageServiceClient.analyzeEntities`.
    func analyzeEntities(
      request: AnalyzeEntitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse

    /// See `LanguageServiceClient.classifyText`.
    func classifyText(
      request: ClassifyTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.ClassifyTextResponse

    /// See `LanguageServiceClient.moderateText`.
    func moderateText(
      request: ModerateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.ModerateTextResponse

    /// See `LanguageServiceClient.annotateText`.
    func annotateText(
      request: AnnotateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnnotateTextResponse
  }
}

// Default implementations
extension Clients.LanguageServiceProtocol {
  public func analyzeSentiment(request: AnalyzeSentimentRequest) async throws
    -> GoogleCloudLanguageV2.AnalyzeSentimentResponse
  {
    try await self.analyzeSentiment(request: request, options: .init())
  }

  public func analyzeSentiment(
    request: AnalyzeSentimentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLanguageV2.AnalyzeSentimentResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func analyzeSentiment(
    document: Document?,
    encodingType: EncodingType,
  ) async throws -> GoogleCloudLanguageV2.AnalyzeSentimentResponse {
    let request = AnalyzeSentimentRequest().with {
      $0.document = document
      $0.encodingType = encodingType
    }
    return try await self.analyzeSentiment(request: request)
  }

  public func analyzeSentiment(
    document: Document?,
  ) async throws -> GoogleCloudLanguageV2.AnalyzeSentimentResponse {
    let request = AnalyzeSentimentRequest().with {
      $0.document = document
    }
    return try await self.analyzeSentiment(request: request)
  }

  public func analyzeEntities(request: AnalyzeEntitiesRequest) async throws
    -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse
  {
    try await self.analyzeEntities(request: request, options: .init())
  }

  public func analyzeEntities(
    request: AnalyzeEntitiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func analyzeEntities(
    document: Document?,
    encodingType: EncodingType,
  ) async throws -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse {
    let request = AnalyzeEntitiesRequest().with {
      $0.document = document
      $0.encodingType = encodingType
    }
    return try await self.analyzeEntities(request: request)
  }

  public func analyzeEntities(
    document: Document?,
  ) async throws -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse {
    let request = AnalyzeEntitiesRequest().with {
      $0.document = document
    }
    return try await self.analyzeEntities(request: request)
  }

  public func classifyText(request: ClassifyTextRequest) async throws
    -> GoogleCloudLanguageV2.ClassifyTextResponse
  {
    try await self.classifyText(request: request, options: .init())
  }

  public func classifyText(
    request: ClassifyTextRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLanguageV2.ClassifyTextResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func classifyText(
    document: Document?,
  ) async throws -> GoogleCloudLanguageV2.ClassifyTextResponse {
    let request = ClassifyTextRequest().with {
      $0.document = document
    }
    return try await self.classifyText(request: request)
  }

  public func moderateText(request: ModerateTextRequest) async throws
    -> GoogleCloudLanguageV2.ModerateTextResponse
  {
    try await self.moderateText(request: request, options: .init())
  }

  public func moderateText(
    request: ModerateTextRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLanguageV2.ModerateTextResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func moderateText(
    document: Document?,
  ) async throws -> GoogleCloudLanguageV2.ModerateTextResponse {
    let request = ModerateTextRequest().with {
      $0.document = document
    }
    return try await self.moderateText(request: request)
  }

  public func annotateText(request: AnnotateTextRequest) async throws
    -> GoogleCloudLanguageV2.AnnotateTextResponse
  {
    try await self.annotateText(request: request, options: .init())
  }

  public func annotateText(
    request: AnnotateTextRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLanguageV2.AnnotateTextResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func annotateText(
    document: Document?,
    features: AnnotateTextRequest.Features?,
    encodingType: EncodingType,
  ) async throws -> GoogleCloudLanguageV2.AnnotateTextResponse {
    let request = AnnotateTextRequest().with {
      $0.document = document
      $0.features = features
      $0.encodingType = encodingType
    }
    return try await self.annotateText(request: request)
  }

  public func annotateText(
    document: Document?,
    features: AnnotateTextRequest.Features?,
  ) async throws -> GoogleCloudLanguageV2.AnnotateTextResponse {
    let request = AnnotateTextRequest().with {
      $0.document = document
      $0.features = features
    }
    return try await self.annotateText(request: request)
  }
}
