// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class LanguageServiceRetry: LanguageServiceStub {
    let inner: any LanguageServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any LanguageServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func analyzeSentiment(
      request: AnalyzeSentimentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnalyzeSentimentResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AnalyzeSentimentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLanguageV2.AnalyzeSentimentResponse
          in
          return try await self.inner.analyzeSentiment(request: r, options: o)
        })
    }

    public func analyzeEntities(
      request: AnalyzeEntitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AnalyzeEntitiesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLanguageV2.AnalyzeEntitiesResponse
          in
          return try await self.inner.analyzeEntities(request: r, options: o)
        })
    }

    public func classifyText(
      request: ClassifyTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.ClassifyTextResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ClassifyTextRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLanguageV2.ClassifyTextResponse
          in
          return try await self.inner.classifyText(request: r, options: o)
        })
    }

    public func moderateText(
      request: ModerateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.ModerateTextResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ModerateTextRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLanguageV2.ModerateTextResponse
          in
          return try await self.inner.moderateText(request: r, options: o)
        })
    }

    public func annotateText(
      request: AnnotateTextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLanguageV2.AnnotateTextResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AnnotateTextRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLanguageV2.AnnotateTextResponse
          in
          return try await self.inner.annotateText(request: r, options: o)
        })
    }
  }
}
